[package]
name = "tab-bar"
version = "0.1.0"
authors = ["Jonah Caplan <jonahcaplan@gmail.com>"]
edition = "2018"
license = "MIT"

[dependencies]
colored = "2"
ansi_term = "0.12"
zellij-tile = { path = "../../zellij-tile" }
