---
version: "2.1"
services:
  zellij-e2e:
    image: ghcr.io/linuxserver/openssh-server
    container_name: zellij-e2e
    hostname: zellij-e2e
    network_mode: host
    environment:
      PUID: 1000
      PGID: 1000
      TZ: Europe/Vienna
      PASSWORD_ACCESS: true
      USER_PASSWORD: test
      USER_NAME: test
    volumes:
      - type: bind
        source: ./target
        target: /usr/src/zellij
      - type: bind
        source: ./src/tests/fixtures
        target: /usr/src/zellij/fixtures
    ports:
      - 2222:2222
    restart: unless-stopped
