---
# Configuration for zellij.

# In order to troubleshoot your configuration try using the following command:
# `zellij setup --check`
# It should show current config locations and features that are enabled.

keybinds:
    unbind: true
    normal:
        - action: [SwitchToMode: Locked,]
          key: [Ctrl: 'g',]
        - action: [SwitchToMode: Pane,]
          key: [Ctrl: 'p',]
        - action: [SwitchToMode: Resize,]
          key: [Ctrl: 'n',]
        - action: [SwitchToMode: Tab,]
          key: [Ctrl: 't',]
        - action: [SwitchToMode: Scroll,]
          key: [Ctrl: 's',]
        - action: [SwitchToMode: Session,]
          key: [Ctrl: 'o',]
        - action: [SwitchToMode: Move,]
          key: [Ctrl: 'h',]
        - action: [SwitchToMode: Tmux,]
          key: [Ctrl: 'b',]
        - action: [Quit,]
          key: [Ctrl: 'q',]
        - action: [NewPane: ]
          key: [ Alt: 'n',]
        - action: [MoveFocusOrTab: Left,]
          key: [ Alt: 'h', Alt: Left]
        - action: [MoveFocusOrTab: Right,]
          key: [ Alt: 'l', Alt: Right ]
        - action: [MoveFocus: Down,]
          key: [ Alt: 'j', Alt: Down]
        - action: [MoveFocus: Up,]
          key: [ Alt: 'k', Alt: Up, ]
        - action: [Resize: Increase,]
          key: [ Alt: '=']
        - action: [Resize: Increase,]
          key: [ Alt: '+']
        - action: [Resize: Decrease,]
          key: [ Alt: '-']
        # uncomment this and adjust key if using copy_on_select=false
        # - action: [Copy: ]
        #   key: [ Alt: 'c']
    locked:
        - action: [SwitchToMode: Normal,]
          key: [Ctrl: 'g',]
    resize:
        - action: [SwitchToMode: Locked,]
          key: [Ctrl: 'g']
        - action: [SwitchToMode: Pane,]
          key: [Ctrl: 'p',]
        - action: [SwitchToMode: Tab,]
          key: [Ctrl: 't',]
        - action: [SwitchToMode: Normal,]
          key: [Ctrl: 'n', Char: "\n", Char: ' ', Esc]
        - action: [SwitchToMode: Scroll,]
          key: [Ctrl: 's']
        - action: [SwitchToMode: Session,]
          key: [Ctrl: 'o',]
        - action: [SwitchToMode: Move,]
          key: [Ctrl: 'h',]
        - action: [SwitchToMode: Tmux,]
          key: [Ctrl: 'b',]
        - action: [Quit]
          key: [Ctrl: 'q']
        - action: [Resize: Left,]
          key: [Char: 'h', Left,]
        - action: [Resize: Down,]
          key: [Char: 'j', Down,]
        - action: [Resize: Up,]
          key: [Char: 'k', Up, ]
        - action: [Resize: Right,]
          key: [Char: 'l', Right,]
        - action: [Resize: Increase,]
          key: [Char: '=']
        - action: [Resize: Increase,]
          key: [ Char: '+']
        - action: [Resize: Decrease,]
          key: [Char: '-']
        - action: [NewPane: ,]
          key: [ Alt: 'n',]
        - action: [MoveFocusOrTab: Left,]
          key: [ Alt: 'h', Alt: Left]
        - action: [MoveFocusOrTab: Right,]
          key: [ Alt: 'l', Alt: Right]
        - action: [MoveFocus: Down,]
          key: [ Alt: 'j', Alt: Down]
        - action: [MoveFocus: Up,]
          key: [ Alt: 'k', Alt: Up]
        - action: [Resize: Increase,]
          key: [ Alt: '=']
        - action: [Resize: Increase,]
          key: [ Alt: '+']
        - action: [Resize: Decrease,]
          key: [ Alt: '-']
    pane:
        - action: [SwitchToMode: Locked,]
          key: [Ctrl: 'g']
        - action: [SwitchToMode: Resize,]
          key: [Ctrl: 'n',]
        - action: [SwitchToMode: Tab,]
          key: [Ctrl: 't',]
        - action: [SwitchToMode: Normal,]
          key: [Ctrl: 'p', Char: "\n", Char: ' ', Esc]
        - action: [SwitchToMode: Scroll,]
          key: [Ctrl: 's']
        - action: [SwitchToMode: Session,]
          key: [Ctrl: 'o',]
        - action: [SwitchToMode: Move,]
          key: [Ctrl: 'h',]
        - action: [SwitchToMode: Tmux,]
          key: [Ctrl: 'b',]
        - action: [Quit,]
          key: [Ctrl: 'q',]
        - action: [MoveFocus: Left,]
          key: [ Char: 'h', Left,]
        - action: [MoveFocus: Right,]
          key: [ Char: 'l', Right,]
        - action: [MoveFocus: Down,]
          key: [ Char: 'j', Down,]
        - action: [MoveFocus: Up,]
          key: [ Char: 'k', Up,]
        - action: [SwitchFocus,]
          key: [Char: 'p']
        - action: [NewPane: , SwitchToMode: Normal,]
          key: [Char: 'n',]
        - action: [NewPane: Down, SwitchToMode: Normal,]
          key: [Char: 'd',]
        - action: [NewPane: Right, SwitchToMode: Normal,]
          key: [Char: 'r',]
        - action: [CloseFocus, SwitchToMode: Normal,]
          key: [Char: 'x',]
        - action: [ToggleFocusFullscreen, SwitchToMode: Normal,]
          key: [Char: 'f',]
        - action: [TogglePaneFrames, SwitchToMode: Normal,]
          key: [Char: 'z',]
        - action: [ToggleFloatingPanes, SwitchToMode: Normal,]
          key: [Char: 'w']
        - action: [TogglePaneEmbedOrFloating, SwitchToMode: Normal,]
          key: [Char: 'e']
        - action: [NewPane: ,]
          key: [ Alt: 'n',]
        - action: [MoveFocusOrTab: Left,]
          key: [ Alt: 'h', Alt: Left]  # The Alt: Left etc. variants are temporary hacks and will be removed in the future - please do not rely on them!
        - action: [MoveFocusOrTab: Right,]
          key: [ Alt: 'l', Alt: Right]
        - action: [MoveFocus: Down,]
          key: [ Alt: 'j', Alt: Down]
        - action: [MoveFocus: Up,]
          key: [ Alt: 'k', Alt: Up]
        - action: [Resize: Increase,]
          key: [ Alt: '=']
        - action: [Resize: Increase,]
          key: [ Alt: '+']
        - action: [Resize: Decrease,]
          key: [ Alt: '-']
        - action: [SwitchToMode: RenamePane, PaneNameInput: [0],]
          key: [Char: 'c']
    move:
        - action: [SwitchToMode: Locked,]
          key: [Ctrl: 'g']
        - action: [SwitchToMode: Pane,]
          key: [Ctrl: 'p',]
        - action: [SwitchToMode: Tab,]
          key: [Ctrl: 't',]
        - action: [SwitchToMode: Resize,]
          key: [Ctrl: 'n',]
        - action: [SwitchToMode: Normal,]
          key: [Ctrl: 'h', Char: "\n", Char: ' ', Esc]
        - action: [SwitchToMode: Scroll,]
          key: [Ctrl: 's']
        - action: [SwitchToMode: Session,]
          key: [Ctrl: 'o',]
        - action: [Quit]
          key: [Ctrl: 'q']
        - action: [MovePane: ,]
          key: [Char: 'n', Char: "\t",]
        - action: [MovePane: Left,]
          key: [Char: 'h', Left,]
        - action: [MovePane: Down,]
          key: [Char: 'j', Down,]
        - action: [MovePane: Up,]
          key: [Char: 'k', Up, ]
        - action: [MovePane: Right,]
          key: [Char: 'l', Right,]
        - action: [NewPane: ,]
          key: [ Alt: 'n',]
        - action: [MoveFocusOrTab: Left,]
          key: [ Alt: 'h', Alt: Left]  # The Alt: Left etc. variants are temporary hacks and will be removed in the future - please do not rely on them!
        - action: [MoveFocusOrTab: Right,]
          key: [ Alt: 'l', Alt: Right]
        - action: [MoveFocus: Down,]
          key: [ Alt: 'j', Alt: Down]
        - action: [MoveFocus: Up,]
          key: [ Alt: 'k', Alt: Up]
        - action: [Resize: Increase,]
          key: [ Alt: '=']
        - action: [Resize: Increase,]
          key: [ Alt: '+']
        - action: [Resize: Decrease,]
          key: [ Alt: '-']
    tab:
        - action: [SwitchToMode: Locked,]
          key: [Ctrl: 'g']
        - action: [SwitchToMode: Pane,]
          key: [Ctrl: 'p',]
        - action: [SwitchToMode: Resize,]
          key: [Ctrl: 'n',]
        - action: [SwitchToMode: Normal,]
          key: [Ctrl: 't', Char: "\n", Char: ' ', Esc]
        - action: [SwitchToMode: Scroll,]
          key: [Ctrl: 's']
        - action: [SwitchToMode: Move,]
          key: [Ctrl: 'h',]
        - action: [SwitchToMode: Tmux,]
          key: [Ctrl: 'b',]
        - action: [SwitchToMode: Session,]
          key: [Ctrl: 'o',]
        - action: [SwitchToMode: RenameTab, TabNameInput: [0],]
          key: [Char: 'r']
        - action: [Quit,]
          key: [Ctrl: 'q',]
        - action: [GoToPreviousTab,]
          key: [ Char: 'h', Left, Up, Char: 'k',]
        - action: [GoToNextTab,]
          key: [ Char: 'l', Right,Down, Char: 'j']
        - action: [NewTab: , SwitchToMode: Normal,]
          key: [ Char: 'n',]
        - action: [CloseTab, SwitchToMode: Normal,]
          key: [ Char: 'x',]
        - action: [ToggleActiveSyncTab, SwitchToMode: Normal,]
          key: [Char: 's']
        - action: [GoToTab: 1, SwitchToMode: Normal,]
          key: [ Char: '1',]
        - action: [GoToTab: 2, SwitchToMode: Normal,]
          key: [ Char: '2',]
        - action: [GoToTab: 3, SwitchToMode: Normal,]
          key: [ Char: '3',]
        - action: [GoToTab: 4, SwitchToMode: Normal,]
          key: [ Char: '4',]
        - action: [GoToTab: 5, SwitchToMode: Normal,]
          key: [ Char: '5',]
        - action: [GoToTab: 6, SwitchToMode: Normal,]
          key: [ Char: '6',]
        - action: [GoToTab: 7, SwitchToMode: Normal,]
          key: [ Char: '7',]
        - action: [GoToTab: 8, SwitchToMode: Normal,]
          key: [ Char: '8',]
        - action: [GoToTab: 9, SwitchToMode: Normal,]
          key: [ Char: '9',]
        - action: [ToggleTab]
          key: [ Char: "\t" ]
        - action: [NewPane: ,]
          key: [ Alt: 'n',]
        - action: [MoveFocusOrTab: Left,]
          key: [ Alt: 'h', Alt: Left]  # The Alt: Left etc. variants are temporary hacks and will be removed in the future - please do not rely on them!
        - action: [MoveFocusOrTab: Right,]
          key: [ Alt: 'l', Alt: Right]
        - action: [MoveFocus: Down,]
          key: [ Alt: 'j', Alt: Down]
        - action: [MoveFocus: Up,]
          key: [ Alt: 'k', Alt: Up]
        - action: [Resize: Increase,]
          key: [ Alt: '=']
        - action: [Resize: Increase,]
          key: [ Alt: '+']
        - action: [Resize: Decrease,]
          key: [ Alt: '-']
    scroll:
        - action: [EditScrollback, SwitchToMode: Normal]
          key: [Char: 'e']
        - action: [SwitchToMode: Normal,]
          key: [Ctrl: 's', Char: ' ', Char: "\n", Esc]
        - action: [SwitchToMode: Tab,]
          key: [Ctrl: 't',]
        - action: [SwitchToMode: Locked,]
          key: [Ctrl: 'g',]
        - action: [SwitchToMode: Pane,]
          key: [Ctrl: 'p',]
        - action: [SwitchToMode: Move,]
          key: [Ctrl: 'h',]
        - action: [SwitchToMode: Tmux,]
          key: [Ctrl: 'b',]
        - action: [SwitchToMode: Session,]
          key: [Ctrl: 'o',]
        - action: [SwitchToMode: Resize,]
          key: [Ctrl: 'n',]
        - action: [ScrollToBottom, SwitchToMode: Normal,]
          key: [Ctrl: 'c',]
        - action: [Quit,]
          key: [Ctrl: 'q',]
        - action: [ScrollDown,]
          key: [Char: 'j', Down,]
        - action: [ScrollUp,]
          key: [Char: 'k', Up,]
        - action: [PageScrollDown,]
          key: [Ctrl: 'f', PageDown, Right, Char: 'l',]
        - action: [PageScrollUp,]
          key: [Ctrl: 'b', PageUp, Left, Char: 'h',]
        - action: [HalfPageScrollDown,]
          key: [Char: 'd',]
        - action: [HalfPageScrollUp,]
          key: [Char: 'u',]
        - action: [NewPane: ,]
          key: [ Alt: 'n',]
        - action: [MoveFocusOrTab: Left,]
          key: [ Alt: 'h', Alt: Left]  # The Alt: Left etc. variants are temporary hacks and will be removed in the future - please do not rely on them!
        - action: [MoveFocusOrTab: Right,]
          key: [ Alt: 'l', Alt: Right]
        - action: [MoveFocus: Down,]
          key: [ Alt: 'j', Alt: Down]
        - action: [MoveFocus: Up,]
          key: [ Alt: 'k', Alt: Up]
        - action: [Resize: Increase,]
          key: [ Alt: '=']
        - action: [Resize: Increase,]
          key: [ Alt: '+']
        - action: [Resize: Decrease,]
          key: [ Alt: '-']
        # uncomment this and adjust key if using copy_on_select=false
        # - action: [Copy: ]
        #   key: [ Alt: 'c']
    renametab:
        - action: [SwitchToMode: Normal,]
          key: [Char: "\n", Ctrl: 'c', Esc]
        - action: [TabNameInput: [27] , SwitchToMode: Tab,]
          key: [Esc,]
        - action: [NewPane: ,]
          key: [ Alt: 'n',]
        - action: [MoveFocusOrTab: Left,]
          key: [ Alt: 'h', Alt: Left]
        - action: [MoveFocusOrTab: Right,]
          key: [ Alt: 'l', Alt: Right]
        - action: [MoveFocus: Down,]
          key: [ Alt: 'j', Alt: Down]
        - action: [MoveFocus: Up,]
          key: [ Alt: 'k', Alt: Up]
        - action: [Resize: Increase,]
          key: [ Alt: '=']
        - action: [Resize: Increase,]
          key: [ Alt: '+']
        - action: [Resize: Decrease,]
          key: [ Alt: '-']
    renamepane:
        - action: [SwitchToMode: Normal,]
          key: [Char: "\n", Ctrl: 'c', Esc]
        - action: [PaneNameInput: [27] , SwitchToMode: Pane,]
          key: [Esc,]
        - action: [NewPane: ,]
          key: [ Alt: 'n',]
        - action: [MoveFocusOrTab: Left,]
          key: [ Alt: 'h', Alt: Left]
        - action: [MoveFocusOrTab: Right,]
          key: [ Alt: 'l', Alt: Right]
        - action: [MoveFocus: Down,]
          key: [ Alt: 'j', Alt: Down]
        - action: [MoveFocus: Up,]
          key: [ Alt: 'k', Alt: Up]
        - action: [Resize: Increase,]
          key: [ Alt: '=']
        - action: [Resize: Increase,]
          key: [ Alt: '+']
        - action: [Resize: Decrease,]
          key: [ Alt: '-']
    session:
        - action: [SwitchToMode: Locked,]
          key: [Ctrl: 'g']
        - action: [SwitchToMode: Resize,]
          key: [Ctrl: 'n',]
        - action: [SwitchToMode: Pane,]
          key: [Ctrl: 'p',]
        - action: [SwitchToMode: Move,]
          key: [Ctrl: 'h',]
        - action: [SwitchToMode: Tmux,]
          key: [Ctrl: 'b',]
        - action: [SwitchToMode: Tab,]
          key: [Ctrl: 't',]
        - action: [SwitchToMode: Normal,]
          key: [Ctrl: 'o', Char: "\n", Char: ' ', Esc]
        - action: [SwitchToMode: Scroll,]
          key: [Ctrl: 's']
        - action: [Quit,]
          key: [Ctrl: 'q',]
        - action: [Detach,]
          key: [Char: 'd',]
        - action: [NewPane: ,]
          key: [ Alt: 'n',]
        - action: [MoveFocusOrTab: Left,]
          key: [ Alt: 'h', Alt: Left]
        - action: [MoveFocusOrTab: Right,]
          key: [ Alt: 'l', Alt: Right]
        - action: [MoveFocus: Down,]
          key: [ Alt: 'j', Alt: Down]
        - action: [MoveFocus: Up,]
          key: [ Alt: 'k', Alt: Up]
        - action: [Resize: Increase,]
          key: [ Alt: '=']
        - action: [Resize: Increase,]
          key: [ Alt: '+']
        - action: [Resize: Decrease,]
          key: [ Alt: '-']
    tmux:
        - action: [SwitchToMode: Locked,]
          key: [Ctrl: 'g']
        - action: [SwitchToMode: Resize,]
          key: [Ctrl: 'n',]
        - action: [SwitchToMode: Pane,]
          key: [Ctrl: 'p',]
        - action: [SwitchToMode: Move,]
          key: [Ctrl: 'h',]
        - action: [SwitchToMode: Tab,]
          key: [Ctrl: 't',]
        - action: [SwitchToMode: Normal,]
          key: [Ctrl: 'o', Char: "\n", Char: ' ', Esc]
        - action: [SwitchToMode: Scroll,]
          key: [Ctrl: 's']
        - action: [SwitchToMode: Scroll,]
          key: [ Char: '[']
        - action: [Quit,]
          key: [Ctrl: 'q',]
        - action: [Write: [2,], SwitchToMode: Normal]
          key: [Ctrl: 'b']
        - action: [NewPane: Down, SwitchToMode: Normal,]
          key: [Char: "\"",]
        - action: [NewPane: Right, SwitchToMode: Normal,]
          key: [Char: '%',]
        - action: [ToggleFocusFullscreen, SwitchToMode: Normal,]
          key: [Char: 'z',]
        - action: [NewTab: , SwitchToMode: Normal,]
          key: [ Char: 'c',]
        - action: [SwitchToMode: RenameTab, TabNameInput: [0],]
          key: [Char: ',']
        - action: [GoToPreviousTab, SwitchToMode: Normal,]
          key: [ Char: 'p']
        - action: [GoToNextTab, SwitchToMode: Normal,]
          key: [ Char: 'n']
        - action: [MoveFocus: Left, SwitchToMode: Normal,]
          key: [ Left,]
        - action: [MoveFocus: Right, SwitchToMode: Normal,]
          key: [ Right,]
        - action: [MoveFocus: Down, SwitchToMode: Normal,]
          key: [ Down,]
        - action: [MoveFocus: Up, SwitchToMode: Normal,]
          key: [ Up,]
        - action: [MoveFocus: Left, SwitchToMode: Normal,]
          key: [ Char: 'h']
        - action: [MoveFocus: Right, SwitchToMode: Normal,]
          key: [ Char: 'l']
        - action: [MoveFocus: Down, SwitchToMode: Normal,]
          key: [ Char: 'j']
        - action: [MoveFocus: Up, SwitchToMode: Normal,]
          key: [ Char: 'k']
        - action: [NewPane: ,]
          key: [ Alt: 'n',]
        - action: [MoveFocusOrTab: Left,]
          key: [ Alt: 'h', Alt: Left]
        - action: [MoveFocusOrTab: Right,]
          key: [ Alt: 'l', Alt: Right]
        - action: [MoveFocus: Down,]
          key: [ Alt: 'j', Alt: Down]
        - action: [MoveFocus: Up,]
          key: [ Alt: 'k', Alt: Up]
        - action: [FocusNextPane,]
          key: [ Char: 'o']
        - action: [Resize: Increase,]
          key: [ Alt: '=']
        - action: [Resize: Increase,]
          key: [ Alt: '+']
        - action: [Resize: Decrease,]
          key: [ Alt: '-']
        - action: [Detach,]
          key: [Char: 'd',]
plugins:
    - path: tab-bar
      tag: tab-bar
    - path: status-bar
      tag: status-bar
    - path: strider
      tag: strider
    - path: compact-bar
      tag: compact-bar

# Choose what to do when zellij receives SIGTERM, SIGINT, SIGQUIT or SIGHUP
# eg. when terminal window with an active zellij session is closed
# Options:
#   - detach (Default)
#   - quit
#on_force_close: quit

# Send a request for a simplified ui (without arrow fonts) to plugins
# Options:
#   - true
#   - false (Default)
#simplified_ui: true

# Choose the path to the default shell that zellij will use for opening new panes
# Default: $SHELL
# default_shell: fish

# Toggle between having pane frames around the panes
# Options:
#   - true (default)
#   - false
#pane_frames: true

# Choose the theme that is specified in the themes section.
# For some examples, see: https://github.com/zellij-org/zellij/tree/main/example/themes
# Default: default
#theme: default

# Choose the mode that zellij uses when starting up.
# Default: normal
#default_mode: locked

# Toggle enabling the mouse mode.
# On certain configurations, or terminals this could
# potentially interfere with copying text.
# Options:
#   - true (default)
#   - false
#mouse_mode: false

# Configure the scroll back buffer size
# This is the number of lines zellij stores for each pane in the scroll back
# buffer. Excess number of lines are discarded in a FIFO fashion.
# Valid values: positive integers
# Default value: 10000
#scroll_buffer_size: 10000

# Provide a command to execute when copying text. The text will be piped to
# the stdin of the program to perform the copy. This can be used with
# terminal emulators which do not support the OSC 52 ANSI control sequence
# that will be used by default if this option is not set.
# Examples:
#copy_command: "xclip -selection clipboard" # x11
#copy_command: "wl-copy"                    # wayland
#copy_command: "pbcopy"                     # osx

# Choose the destination for copied text
# Allows using the primary selection buffer (on x11/wayland) instead of the system clipboard.
# Does not apply when using copy_command.
# Options:
#   - system (default)
#   - primary
#copy_clipboard: primary

# Enable or disable automatic copy (and clear) of selection when releasing mouse
#copy_on_select: true

# Path to the default editor to use to edit pane scrollbuffer
# scrollback_editor: /usr/bin/nano
