[package]
name = "zellij-client"
version = "0.28.0"
authors = ["Kunal Mohan <kunalmohan99@gmail.com>"]
edition = "2021"
description = "The client-side library for Zellij"
license = "MIT"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
mio = { version = "0.7.11", features = ['os-ext'] }
zellij-utils = { path = "../zellij-utils/", version = "0.28.0" }
zellij-tile = { path = "../zellij-tile/", version = "0.28.0" }
log = "0.4.16"

[dev-dependencies]
insta = "1.6.0"

[features]

