[package]
name = "zellij-client"
version = "0.24.0"
authors = ["Kunal Mohan <kunalmohan99@gmail.com>"]
edition = "2021"
description = "The client-side library for Zellij"
license = "MIT"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
mio = "0.7.11"
termbg = "0.2.3"
zellij-utils = { path = "../zellij-utils/", version = "0.24.0" }
zellij-tile = { path = "../zellij-tile/", version = "0.24.0" }
log = "0.4.14"
terminfo = "0.7.3"

[dev-dependencies]
insta = "1.6.0"

