[package]
name = "zellij-client"
version = "0.13.0"
authors = ["Kunal Mohan <kunalmohan99@gmail.com>"]
edition = "2018"
description = "The client-side library for Zellij"
license = "MIT"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
termbg = "0.2.3"
zellij-utils = { path = "../zellij-utils/", version = "0.13.0" }

[features]
test = ["zellij-utils/test"]
